name: ant_icons_plus
description: Ant Design icon pack for Flutter providing comprehensive icon coverage, easy integration via font assets, and ready-to-use widgets for apps.
version: 2.0.0
homepage: https://github.com/ocostalucas/ant_icons_plus
license: MIT

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: AntIcons
      fonts:
        - asset: lib/fonts/AntIcons.ttf
