import 'dart:convert';
import 'dart:io';

import 'config.dart';
import 'models.dart';
import 'svg_builder.dart';

// ─── Font Generator ──────────────────────────────────────────────────────────

/// Writes standalone SVG files for each icon to the temp directory.
void writeSvgFiles(List<IconEntry> icons) {
  final dir = Directory(kTempSvgDir);
  if (dir.existsSync()) dir.deleteSync(recursive: true);
  dir.createSync(recursive: true);

  for (final icon in icons) {
    final filename = '${icon.name}-${icon.theme}.svg';
    final svg = buildStandaloneSvg(icon);
    File('$kTempSvgDir/$filename').writeAsStringSync(svg);
  }
}

/// Runs the font generation script (Node.js wrapper around fantasticon).
Future<void> runFantasticon() async {
  final fontDir = Directory(kTempFontDir);
  if (!fontDir.existsSync()) fontDir.createSync(recursive: true);

  final result = await Process.run('node', [
    'tools/generate_font.js',
    kTempSvgDir,
    kTempFontDir,
    kFontFamily,
  ], runInShell: true);

  if (result.exitCode != 0) {
    stderr.writeln('Font generation failed:');
    stderr.writeln(result.stderr);
    stderr.writeln(result.stdout);
    exit(1);
  }
}

/// Reads the codepoints JSON generated by fantasticon.
Map<String, int> readCodepoints() {
  final file = File('$kTempFontDir/$kFontFamily.json');
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  return json.map((key, value) => MapEntry(key, value as int));
}

/// Copies the generated TTF to lib/fonts/.
void copyFont() {
  final fontDir = Directory(kFontDir);
  if (!fontDir.existsSync()) fontDir.createSync(recursive: true);
  File('$kTempFontDir/$kFontFamily.ttf').copySync(kFontFile);
}

/// Cleans up temp directory.
void cleanTemp() {
  final dir = Directory(kTempDir);
  if (dir.existsSync()) dir.deleteSync(recursive: true);
}
